GET http://localhost:5000/api/items/goal/5d29f83232d06e1af8e7a02b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkMjlmN2JiMzJkMDZlMWFmOGU3YTAyYSIsIm5hbWUiOiJUTiIsImlhdCI6MTU2MzAzNTI3MSwiZXhwIjoxNTYzMDM4ODcxfQ.iGTM6j2d5Dfo8nsREqOxISgAc73qHfYBKCcBfoXTf9w


