GET http://localhost:5000/api/items/myitems
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNDVkZDQzOTk4NjRhNDIzODIxNmI5MyIsIm5hbWUiOiJIYXNhbiBTaGVpa2giLCJpYXQiOjE1NjUxOTQxMTgsImV4cCI6MTU2NTE5NzcxOH0.pMldz-LkN4F1PyhSmBODsgXN36EMIfqbnp9rJMIYQ0Y

{
    "name": "Macbook Pro 15-inch",
    "price": "10,499",
    "url": "https://www.apple.com/my/shop/buy-mac/macbook-pro/15-inch"
}